version: '3.7'
services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
    ports:
      - "9042:9042"

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    networks:
      - cassandra-net
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2

networks:
  cassandra-net:
